/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogContentNodeEditingAddInputForm: typeof import('./src/components/dialog/content/nodeEditing/AddInputForm.vue')['default']
    DialogContentNodeEditingAddOutputForm: typeof import('./src/components/dialog/content/nodeEditing/AddOutputForm.vue')['default']
    DialogContentNodeEditingDialogContent: typeof import('./src/components/dialog/content/NodeEditingDialogContent.vue')['default']
    DialogContentNodeEditingRemoveInputForm: typeof import('./src/components/dialog/content/nodeEditing/RemoveInputForm.vue')['default']
    DialogContentNodeEditingRemoveOutputForm: typeof import('./src/components/dialog/content/nodeEditing/RemoveOutputForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
